Braedon
icssc-projects/AntAlmanac pull request #42
Opened 2020-12-07 03:14 UTC by braedons

**Summary**
The state `addedCourse` was created for SectionTableBody. It becomes true when the add button is clicked in a class search, or upon creation for the row, if the course is already in the list of added ones.

The html class `addedCourse` was also created, and is added to the row if the state `addedCourse` is true.

The function to set the state was also added to the objects in the addedCourses array to allow for removing highlights.

![image](https://user-images.githubusercontent.com/25188285/101305145-d8941d00-37f6-11eb-9ec6-f41c01f148d7.png)
![image](https://user-images.githubusercontent.com/25188285/101305173-e8136600-37f6-11eb-804b-09cf76c52b1d.png)

**Test Plan**
- Verify that clicking add highlights the corresponding row
- Verify that deleting a course from the schedule removes the highlight
- Verify that all courses are highlighted in the Added Classes tab
- Verify that switching schedule numbers highlights only the corresponding courses
- Verify that doing a new search retains highlights

**Issues**
#26

2020-12-09 10:23 UTC, ChaseC99 requested changes
Great work on this! Looks awesome and seems like it works perfectly. Even works when you switch schedules 👏 

I have a few comments but once those are resolved, it should be good to go.

2020-12-09 10:23 UTC, ChaseC99 commented on client/src/components/SectionTable/SectionTableBody.js
> +        <tr className={classes.tr + addedCourseStr}>
We should probably use [classnames](https://github.com/JedWatson/classnames) here. 

The library is already in the project, so we can just import it at the top
```javascript
import classNames from 'classnames';
```

And use it in the return
```javascript
return (
    <tr className={classNames(classes.tr, {"addedCourse": addedCourse})}>
```

2020-12-20 18:22 UTC, ChaseC99 commented
I missed this in my first Code Review, but it looks like an older version of the backend submodule was also accidentally committed.

Try running `git submodule update` and commit the change to bring it back up to date.

2020-12-20 22:16 UTC, braedons commented
I ran that command, but there was no output. `git status` also shows no changes.

2020-12-23 07:39 UTC, ChaseC99 commented on client/src/components/Calendar/calendar.css
> +    justify-content: center;
LGTM!

2020-12-24 04:50 UTC, devsdevsdevs commented
First, sorry for the massive massive delay on this review. 
I was trying to think of a better way to implement this change as I didn't really feel that we needed to pass the state modifying function around to make the state changes. 
Instead, I implemented a lookup table into AppStore and the `SectionTableBody` component responds to changes when courses are added/removed and when the schedule number is changed. This is less confusing and more in line with React patterns. However, this is more computationally expensive as every SectionTableBody will need to check the lookup table when courses are added or the schedule index is changed, but in practice, the performance impact is very negligible. You can check out the changes in the `section-highlight` branch. Nonetheless, thank you again for your effort, description and test plan.

2021-01-13 08:25 UTC, devsdevsdevs commented
I've cherry picked and pushed the latest commit from here (a24180b) to develop. Can you please close this branch and address other issues within their own branches?

2021-01-17 01:11 UTC, closed without merging